---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mgbrodi
spec:
  memberOf: [guests]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: [kubernetes-auto-ingested]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: kubernetes-auto-ingested
spec:
  type: team
  children: []
